### ISSUE TITLE
incorrect display of the tab processing view using Safari style

### ISSUE THREAD

**Issue by vannip** [MiMo42/MMTabBarView#21]
Hi,

You can see the weird white line above the spinning view on the demo app
Just set safari style and check the "processing" flag

![schermata 2014-01-15 alle 13 59 00](https://f.cloud.github.com/assets/1543577/1925578/fa9db4c6-7e33-11e3-9f5b-17ace7ac8f0a.png)

tried on 10.7 and 10.9

I know i can live with that...but maybe is trivial for you to fix it. Thanks anyway :+1:

**Comment by vannip** [comment]
hi chinhster! I'm so late and so sorry for that but i wanted to thank you for your time regarding the issue i pointed out.
I finally had the chance to try your approach putting your `(NSRect)indicatorRectForBounds:(NSRect)theRect ofTabCell:(MMTabBarButtonCell *)cell` in MMSafariTabStyle since that's the style i'm currently using.
It works but only if i use directly the `drawingRect` instead of the `constrainedDrawingRect`. If i use the latter and frame it with `NSFrameRect` i can see that rect is left shifted by an unknown amount. Using the former, on the other hand, seems to yield the desired results.
Here are some screenshots:
- using constrainedDrawingRect:
![constraintdrawingrect](https://cloud.githubusercontent.com/assets/1543577/6211227/3c512c04-b5d8-11e4-861a-991f99c0d241.png)
- using unprocessed drawingRect:
![drawingrect](https://cloud.githubusercontent.com/assets/1543577/6211232/458dc12e-b5d8-11e4-9239-738baeef712c.png)

Do you think it's viable?
Thank you,

Vanni

**Comment by chinhster** [comment]
I can't remember why I suggested adding indicatorRectForBounds:ofTabCell: into the style instead.  Perhaps it was to minimize the changes to the common source.  I personally just use kMMTabBarIndicatorHeight and hit the rest of the code that affect the height.

**Comment by vannip** [comment]
yeah i can see the minimize changes to common source point and that's exactly why i tried to take that path at first glance. I'll go with that and see if its sustainable.
Thanks
