### ISSUE TITLE
display object count on tab

### ISSUE THREAD

**Issue by vannip** [MiMo42/MMTabBarView#29]
An open question...maybe i'm dumb and doing something wrong but...

should `-(BOOL)showObjectCount` be a method declared in MMTabBarItem protocol, like the other optional ones?
It doesn't seem to be there and i figured out after an hour of tinkering that this is called on the
tabItem identifier and is expected to return YES in order to show the counter on the attached tab.
`-(NSInteger)objectCount` is still called even if the `id<MMTabBarItem>` instance doesn't implement the aforementioned method, but the counter is, as a matter of fact, not displayed.

Thanks for any clarifications about that.
Vanni

**Comment by MiMo42** [comment]
Property showObjectCountHas been added (develop branch, SHA 617adf6f4da7a98661dfa6449e4c9ae3b5f5a32b)
