### ISSUE TITLE
NSViewNoIntrinsicMetric

### ISSUE THREAD

**Issue by balthisar** [MiMo42/MMTabBarView#40]
I've got it working, but the use of this threw me for a loop when a 10.10.5 user of my application reported an access fault (my fault for not testing on 10.10 first!). Specifically `NSViewNoIntrinsicMetric` corrects the deprecated typo `NSViewNoInstrinsicMetric`, but according to the header the "correct" version carries the macro `NS_AVAILABLE_MAC(10_11)`.

Given that the typo'd version is only commented as deprecated but not formally deprecated, is the intention that MMTabBarView have a deployment target of 10.11 or newer, too? It works perfectly fine on 10.10.5 by going back to the previous constant, and the readme still indicates 10.9+.

I'm happy to issue a PR, but maybe I'm missing something else here.

**Comment by balthisar** [comment]
> I'm happy to issue a PR, but maybe I'm missing something else here.

Added PR #41.

**Comment by MiMo42** [comment]
WTF... :-)
