### ISSUE TITLE
Can't build MMTabBarView - see error code

### ISSUE THREAD

**Issue by tomatoTom** [MiMo42/MMTabBarView#43]
Hello everyone! :)

I can't build the demo project with Xcode 8.0 and 7.x.
There is always this error:

`dyld: Library not loaded: @rpath/MMTabBarView.framework/Versions/A/MMTabBarView
  Referenced from: /Users/julian/Library/Developer/Xcode/DerivedData/MMTabBarView_Demo-arjpuxyfsaerygdqyqgswnrdcxgi/Build/Products/Debug/MMTabBarView Demo.app/Contents/MacOS/MMTabBarView Demo
  Reason: image not found
(lldb)`

Can anybody help me? Thanks a lot!

**Comment by DivineDominion** [comment]
Works fine for me on Version 7.3.1 (7D1014). I know this from my own projects when I forget to drag the framework into "Embedded Binaries", though.
