### ISSUE TITLE
No hightlight style for selected tab when using yosemite tab style

### ISSUE THREAD

**Issue by treblam** [MiMo42/MMTabBarView#50]
There is no highlight style for selected tab when using yosemite tab style. See image below:

![image](https://cloud.githubusercontent.com/assets/215470/21072293/26f69d8c-bef8-11e6-9b42-a6c8c97e99cb.png)

The second bar is the selected tab, and thus should be highlighted.

**Comment by MiMo42** [comment]
Just set the colors of your yosemite tab style.
There are two properties: selectedTabColor and unselectedTabColor.

Additionally you'll find a change in colors for selected/deselected tabs in active/inactive windows in the development branch.
