### ISSUE TITLE
Doesn't switch appearance for Dark Mode (10.14)

### ISSUE THREAD

**Issue by balthisar** [MiMo42/MMTabBarView#61]
In Mojava preview (10.14), tabs don't change appearance when Dark Mode is active, although the font does change.

I'll take a stab at it in the near future if no one else steps up.

**Comment by balthisar** [comment]
Addressed in #62. Note that the PR updates the deployment target to 10.10, which is I think is finally due.

In addition to dark mode support as reported in the issue, I think this is the first tab style to also support high contrast mode, as well as provide proper dimming appearance when the window is not active.

Enjoy!

**Comment by RobFog** [comment]
> @balthisar 10.14 has been superseded.

What do you mean by that? 10.15 also has Dark Mode.

**Comment by balthisar** [comment]
This issue refers to a PR that was merged several years ago. I'm not really sure what the penultimate comment is referring to, but given the merged PR, I think I'll close this.
